# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-23 11:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pet', '0002_auto_20180422_1447'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('askname', models.CharField(max_length=20)),
                ('receivename', models.CharField(max_length=20)),
                ('seed', models.CharField(max_length=20)),
                ('price', models.CharField(max_length=20)),
                ('time', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=20)),
                ('evaluation', models.IntegerField(default=100)),
                ('picture', models.CharField(max_length=100)),
                ('information', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='guy',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='guy',
            name='address',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='guy',
            name='animal_info',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='guy',
            name='information',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='guy',
            name='picture',
            field=models.CharField(max_length=100),
        ),
    ]
