# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-23 12:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pet', '0004_sort'),
    ]

    operations = [
        migrations.AddField(
            model_name='sort',
            name='resultname',
            field=models.CharField(default='#', max_length=200),
        ),
    ]
