# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-24 07:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pet', '0005_sort_resultname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deal',
            name='state',
        ),
        migrations.AddField(
            model_name='deal',
            name='askstate',
            field=models.CharField(default='\u7b49\u5f85\u5bf9\u65b9\u786e\u8ba4', max_length=20),
        ),
        migrations.AddField(
            model_name='deal',
            name='receivestate',
            field=models.CharField(default='\u672a\u5b8c\u6210', max_length=20),
        ),
    ]
