# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-24 07:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pet', '0006_auto_20180424_1551'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deal',
            old_name='askstate',
            new_name='state',
        ),
        migrations.RemoveField(
            model_name='deal',
            name='receivestate',
        ),
    ]
