# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-30 11:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pet', '0007_auto_20180424_1558'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postname', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=20)),
                ('text', models.CharField(max_length=100)),
                ('time', models.CharField(max_length=20)),
                ('comments', models.CharField(max_length=20)),
                ('picture', models.CharField(max_length=20)),
            ],
        ),
    ]
